apiVersion: bbtoc/v1alpha
kind: Project
metadata:
  name: "logging"
  vendor: "Elastic"
  description: "Reliably and security take data form any source, in any format, then search, analyze, and visualize it in real time."
  website:
    - "https://www.elastic.co/elastic-stack/"
  sourceCode:
    - "https://github.com/elastic/elasticsearch"
    - "https://github.com/elastic/kibana"
  license:
    - "Elastic License 2.0"
    - "SSPLv1"
  purpose: "Elastic and Kibana are used as part of the default logging stack in BB clusters for aggregating, searching, and visualizing logs."
  maturityLevel: "Incubating"
  contacts:
    - name: Kavitha Thulasiraman
      repo1user: '@kavitha'
    - name: Ryan Garcia
      repo1user: '@ryan.j.garcia'
    - name: Evan Rush
      repo1user: '@evan.rush'
    - name: Ronnie Webb
      repo1user: '@ronwebb'
spec:
  packages:
    - name: "elasticsearch-kibana"
      repository: "https://repo1.dso.mil/platform-one/big-bang/apps/core/elasticsearch-kibana"

  images:
    # Incubating: Name of the image
    - name: "docker pull registry1.dso.mil/ironbank/elastic/elasticsearch/elasticsearch:7.17.1"
    - name: "docker pull registry1.dso.mil/ironbank/elastic/kibana/kibana:7.16.2"

      # Incubating: Iron Bank approval request (https://repo1.dso.mil/dsop/<your project>/-/issues/1)
      repository: "https://ironbank.dso.mil/repomap/parent?vendor=Elastic&product=elasticsearch&page=1&sort=1"

      # Graduated: Iron Bank approval URL (https://ironbank.dso.mil/repomap/details;registry1Path=<your project path>)
      approval: "https://ironbank.dso.mil/repomap/parent?vendor=Elastic&product=elasticsearch&page=1&sort=1"

    # Graduated: Links to required documentation
    documentation: [ ]

    # Name and date of required verifications (e.g. "John Doe, 7 Dec 2021")
    signOffs:

      # Sandbox: Verify required files (e.g. LICENSE, CODEOWNERS, CONTRIBUTING.md) in git repository
      requiredFiles: "Andrew Greene, 28 FEB 2022"

      # Sandbox: Demonstratable product
      productDemonstration: "Andrew Greene, 28 FEB 2022"

      # Incubating: demonstrated support through contributions and feature releases
      committedSupport: "Andrew Greene, 28 FEB 2022"

      # Graduated: Full Big Bang implementation
      bigbangImplementation: ""

      # Graduated: Deployable against documented use cases
      productDeployable: ""

      # Graduated: Security support documentation
      securityDocs: ""

      # Graduated: Cyber security review and penetration testing
      cybersecurity: ""
