apiVersion: bbtoc/v1alpha
kind: Project
# NOTE: Remove lines that are not applicable
metadata:
  # Sandbox: Name of the product to be evaluated
  name: Kyverno

  # Sandbox: Product vendor (opensource if no vendor)
  vendor: Nirmata

  # Sandbox: Short description of the product
  description: Kyverno is a policy enforcement engine native to Kubernetes

  # Sandbox: URL(s) to product website for further information
  website:
  - https://kyverno.io/

  # Sandbox: product source code repositories (e.g. github.com).  If not opensource, put "Proprietary"
  sourceCode:
  - https://github.com/kyverno/kyverno
  - https://github.com/kyverno/policy-reporter

  # Sandbox: Product licenses (e.g. Apache 2.0, GPL 3.0, MIT, Proprietary).  Include both free and paid tiers if they exist.
  license:
  - Apache 2.0
  - MIT License

  # Maturity level of the package
  maturityLevel: Incubating # Sandbox, Incubating, or Graduated

  # Sandbox: Points of contact for project (at least 2)
  contacts:
  - name: Michael McLeroy
    repo1user: '@michaelmcleroy'
  - name: Tunde Oladipupo
    repo1user: '@toladipupo'
  - name: "Ernest Chuang"
    repo1user: "@echuang"

spec:
  # Sandbox: Package(s) contained in the product (e.g. operator and application).  Each package will have its own repository in repo1.
  packages:
    # Sandbox: Name of the package
  - name: Kyverno

    # Sandbox: Big Bang repository (i.e. https://repo.dso.mil/platform-one/big-bang/apps/sandbox/<your project>)
    repository: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno

    # Incubating: List of images contained in the package.
    images:
      - name: Kyverno
        repository: https://repo1.dso.mil/dsop/nirmata/kyverno
        approval: https://ironbank.dso.mil/repomap/details;registry1Path=nirmata%252Fkyverno
      - name: Kyverno Preinstall
        repository: https://repo1.dso.mil/dsop/nirmata/kyverno-pre
        approval: https://ironbank.dso.mil/repomap/details;registry1Path=nirmata%252Fkyvernopre
  - name: Kyverno Policies
    repository: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno-policies
    image: []
  - name: Kyverno Reporter
    repository: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno-reporter
    images:
      - name: Policy Reporter
        repository: https://repo1.dso.mil/dsop/nirmata/policy-reporter/policy-reporter
        approval: https://ironbank.dso.mil/repomap/details;registry1Path=nirmata%252Fpolicy-reporter%252Fpolicy-reporter

    # Graduated: Links to required documentation
    documentation:
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/charter/packages/kyverno/Architecture.md
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/charter/BigBangPackages.md#kyverno
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/understanding-bigbang/licensing-expectations.md
    - (MISSING) https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/guides/prerequisites/minimum-hardware-requirements.md

  # Name and date of required verifications (e.g. "John Doe, 7 Dec 2021")
  signOffs:

    # Sandbox: Verification of requirements
    sandboxVerification: Michael McLeroy, 12 Jul 2022

    # Incubating: Verification of requirements
    incubatingVerification: Michael McLeroy, 12 Jul 2022

    # Graduated: Verification of requirements
    graduatedVerification: ""
    # Items missing: Monitoring integration using Kyverno Reporter