apiVersion: bbtoc/v1alpha
kind: Project
# NOTE: Remove lines that are not applicable
metadata:
  # Sandbox: Name of the product to be evaluated
  name: Loki

  # Sandbox: Product vendor (opensource if no vendor)
  vendor: Grafana Labs

  # Sandbox: Short description of the product
  description: Loki is a log aggregation system designed to store and query logs from all your applications and infrastructure.

  # Sandbox: URL(s) to product website for further information
  website:
  - https://grafana.com/oss/loki/

  # Sandbox: product source code repositories (e.g. github.com).  If not opensource, put "Proprietary"
  sourceCode:
  - https://github.com/grafana/loki

  # Sandbox: Product licenses (e.g. Apache 2.0, GPL 3.0, MIT, Proprietary).  Include both free and paid tiers if they exist.
  license:
  - GNU Affero GPL 3.0
  - Apache 2.0

  # Maturity level of the package
  maturityLevel: Incubating # Sandbox, Incubating, or Graduated

  # Sandbox: Points of contact for project (at least 2)
  contacts:
  - name: Jay Goodson
    repo1user: '@jgoodson'
  - name: Ryan Garcia
    repo1user: '@ryan.j.garcia'
  - name: Brandt Keller
    repo1user: '@brandt.w.keller'
  - name: Chris Nuber
    repo1user: '@rancherchris'
spec:
  # Sandbox: Package(s) contained in the product (e.g. operator and application).  Each package will have its own repository in repo1.
  packages:
    # Sandbox: Name of the package
  - name: Loki

    # Sandbox: Big Bang repository (i.e. https://repo.dso.mil/platform-one/big-bang/apps/sandbox/<your project>)
    repository: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/loki

    # Incubating: List of images contained in the package.
    images:
      # Incubating: Name of the image
      - name: Loki
        repository: https://repo1.dso.mil/dsop/opensource/grafana/loki
        approval: https://ironbank.dso.mil/repomap/details;registry1Path=opensource%252Fgrafana%252Floki

    # Graduated: Links to required documentation
    documentation:
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/understanding-bigbang/package-architecture/loki.md
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/packages.md
    # - (MISSING) https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/understanding-bigbang/licensing-model.md
    # - (MISSING) https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/prerequisites/minimum-hardware-requirements.md

  # Name and date of required verifications (e.g. "John Doe, 7 Dec 2021")
  signOffs:

    # Sandbox: Verification of requirements
    sandboxVerification: Michael McLeroy, 13 Jul 2022

    # Incubating: Verification of requirements
    incubatingVerification: Michael McLeroy, 4 Jan 2023

    # Graduated: Verification of requirements
    graduatedVerification: ""
