apiVersion: bbtoc/v1alpha
kind: Project
# NOTE: Remove lines that are not applicable
metadata:
  # Sandbox: Name of the product to be evaluated
  name: "Istio"

  # Sandbox: Product vendor (opensource if no vendor)
  vendor: ""

  # Sandbox: Short description of the product
  description: "Service mesh"

  # Sandbox: URL(s) to product website for further information
  website:
  - "https://istio.io/"

  # Sandbox: product source code repositories (e.g. github.com).  If not opensource, put "Proprietary"
  sourceCode:
  - "https://github.com/istio/istio"

  # Sandbox: Product licenses (e.g. Apache 2.0, GPL 3.0, MIT, Proprietary).  Include both free and paid tiers if they exist.
  license:
  - "Apache 2.0"

  # Sandbox: Value the product brings to the Big Bang community
  purpose: "Service Mesh to provide ingress, mTLS and authorization policies"

  # Maturity level of the package
  maturityLevel: Graduated # Sandbox, Incubating, or Graduated

  # Sandbox: Points of contact for project (at least 2)
  contacts:
  - name: "Thomas Runyon"
    repo1user: "@runyontr"
  - name: Blake Burhart
    repo1user: '@blake.burhart'
  - name: Michael McLeroy
    repo1user: '@michaelmcleroy'

spec:
  # Sandbox: Package(s) contained in the product (e.g. operator and application).  Each package will have its own repository in repo1.
  packages:
    # Sandbox: Name of the package
  - name: "istio-controlplane"

    # Sandbox: Big Bang repository (i.e. https://repo.dso.mil/platform-one/big-bang/apps/sandbox/<your project>)
    repository: "https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane"

    # Incubating: List of images contained in the package.
    images:
      - name: "istio-cni"
        repository: "https://repo1.dso.mil/dsop/opensource/istio/1.11/install-cni"
        approval: "https://ironbank.dso.mil/repomap/details;registry1Path=opensource%252Fistio%252Finstall-cni?page=1&sort=1"
      - name: proxyv2
        repository: https://repo1.dso.mil/dsop/opensource/istio/1.11/proxyv2
        approval: https://ironbank.dso.mil/repomap/details;registry1Path=opensource%252Fistio%252Fproxyv2?page=1&sort=1
      - name: pilot
        repository: https://repo1.dso.mil/dsop/opensource/istio/1.11/pilot
        approval: https://ironbank.dso.mil/repomap/details;registry1Path=opensource%252Fistio%252Fpilot?page=1&sort=1

  - name: istio-operator
    repository: https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator
    images:
    - name: operator
      repository: https://repo1.dso.mil/dsop/opensource/istio/1.11/operator
      approval: https://ironbank.dso.mil/repomap/details;registry1Path=opensource%252Fistio%252Foperator?page=1&sort=1
    # Graduated: Links to required documentation
    documentation: []

  # Name and date of required verifications (e.g. "John Doe, 7 Dec 2021")
  signOffs:

    # Sandbox: Verify required files (e.g. LICENSE, CODEOWNERS, CONTRIBUTING.md) in git repository
    requiredFiles: "Thomas Runyon, 7 Feb 2022"

    # Sandbox: Demonstratable product
    productDemonstration: "Thomas Runyon, 7 Feb 2022"

    # Incubating: demonstrated support through contributions and feature releases
    committedSupport: "Thomas Runyon, 7 Feb 2022"

    # Graduated: Full Big Bang implementation
    bigbangImplementation: "Thomas Runyon, 7 Feb 2022"

    # Graduated: Deployable against documented use cases
    productDeployable: "Thomas Runyon, 7 Feb 2022"

    # Graduated: Security support documentation
    securityDocs: "Thomas Runyon, 7 Feb 2022"

    # Graduated: Cyber security review and penetration testing
    cybersecurity: "Thomas Runyon, 7 Feb 2022"

