apiVersion: bbtoc/v1alpha
kind: Project
# NOTE: Remove lines that are not applicable
metadata:
  # Sandbox: Name of the product to be evaluated
  name: OPA Gatekeeper

  # Sandbox: Product vendor (opensource if no vendor)
  vendor: CNCF

  # Sandbox: Short description of the product
  description: >-
    Gatekeeper provides automated policy enforcement for Kubernetes

  # Sandbox: URL(s) to product website for further information
  website:
  - https://open-policy-agent.github.io/gatekeeper

  # Sandbox: product source code repositories (e.g. github.com).  If not opensource, put "Proprietary"
  sourceCode:
  - https://github.com/open-policy-agent/gatekeeper

  # Sandbox: Product licenses (e.g. Apache 2.0, GPL 3.0, MIT, Proprietary).  Include both free and paid tiers if they exist.
  license:
  - Apache 2.0

  # Maturity level of the package
  maturityLevel: Graduated # Sandbox, Incubating, or Graduated

  # Maintenance Track of the package
  maintenanceTrack: BigBangIntegrated # BigBangIntegrated, BigBangMaintained, CommunityMaintained

  # Sandbox: Points of contact for project (at least 2)
  contacts:
  - name: Michael McLeroy
    repo1user: '@michaelmcleroy'
  - name: Tunde Oladipupo
    repo1user: '@toladipupo'
  - name: "Ernest Chuang"
    repo1user: "@echuang"

spec:
  # Sandbox: Package(s) contained in the product (e.g. operator and application).  Each package will have its own repository in repo1.
  packages:
    # Sandbox: Name of the package
  - name: Gatekeeper

    # Sandbox: Big Bang repository (i.e. https://repo.dso.mil/platform-one/big-bang/apps/sandbox/<your project>)
    repository: https://repo1.dso.mil/platform-one/big-bang/apps/core/policy

    # Incubating: List of images contained in the package.
    images:
      # Incubating: Name of the image
      - name: Gatekeeper

        # Incubating: Iron Bank approval request (https://repo1.dso.mil/dsop/<your project>/-/issues/1)
        repository: https://repo1.dso.mil/dsop/opensource/openpolicyagent/gatekeeper

        # Graduated: Iron Bank approval URL (https://ironbank.dso.mil/repomap/details;registry1Path=<your project path>)
        approval: https://ironbank.dso.mil/repomap/details;registry1Path=opensource%252Fopenpolicyagent%252Fgatekeeper

    # Graduated: Links to required documentation
    documentation:
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/charter/packages/opa-gatekeeper/Architecture.md
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/charter/BigBangPackages.md#opa-gatekeeper
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/understanding-bigbang/licensing-expectations.md
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/guides/prerequisites/minimum-hardware-requirements.md

  # Name and date of required verifications (e.g. "John Doe, 7 Dec 2021")
  signOffs:

    # Sandbox: Verification of requirements
    sandboxVerification: Michael McLeroy, 12 Jul 2022

    # Incubating: Verification of requirements
    incubatingVerification: Michael McLeroy, 12 Jul 2022

    # Graduated: Verification of requirements
    graduatedVerification: Michael McLeroy, 12 Jul 2022