apiVersion: bbtoc/v1alpha
kind: Project
# NOTE: Remove lines that are not applicable
metadata:
  # Sandbox: Name of the product to be evaluated
  name: Sonarqube

  # Sandbox: Product vendor (opensource if no vendor)
  vendor: SonarSource

  # Sandbox: Short description of the product
  description: Static code analysis

  # Sandbox: URL(s) to product website for further information
  website:
  - https://www.sonarqube.org/

  # Sandbox: product source code repositories (e.g. github.com).  If not opensource, put "Proprietary"
  sourceCode:
  - https://github.com/SonarSource/sonarqube

  # Sandbox: Product licenses (e.g. Apache 2.0, GPL 3.0, MIT, Proprietary).  Include both free and paid tiers if they exist.
  license:
  - GNU Lesser GPL 3.0

  # Maturity level of the package
  maturityLevel: Graduated # Sandbox, Incubating, or Graduated

  # Maintenance Track of the package
  maintenanceTrack: BigBangIntegrated # BigBangIntegrated, BigBangMaintained, CommunityMaintained

  # Sandbox: Points of contact for project (at least 2)
  contacts:
  - name: Kevin Wilder
    repo1user: '@kevin.wilder'
  - name: Lynn Still
    repo1user: '@lynnstill'
  - name: Branden Cobb
    repo1user: '@brandencobb'

spec:
  # Sandbox: Package(s) contained in the product (e.g. operator and application).  Each package will have its own repository in repo1.
  packages:
    # Sandbox: Name of the package
  - name: SonarQube

    # Sandbox: Big Bang repository (i.e. https://repo.dso.mil/platform-one/big-bang/apps/sandbox/<your project>)
    repository: https://repo1.dso.mil/platform-one/big-bang/apps/developer-tools/sonarqube

    # Incubating: List of images contained in the package.
    images:
      - name: SonarQube Community
        repository: https://repo1.dso.mil/dsop/big-bang/sonarqube
        approval: https://ironbank.dso.mil/repomap/details;registry1Path=big-bang%252Fsonarqube

    # Graduated: Links to required documentation
    documentation:
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/charter/packages/sonarqube/Architecture.md
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/charter/BigBangPackages.md#sonarqube
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/guides/using-bigbang/default-credentials.md
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/understanding-bigbang/licensing-expectations.md
    - https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/docs/guides/prerequisites/minimum-hardware-requirements.md

  # Name and date of required verifications (e.g. "John Doe, 7 Dec 2021")
  signOffs:

    # Sandbox: Verification of requirements
    sandboxVerification: Michael McLeroy, 13 Jul 2022

    # Incubating: Verification of requirements
    incubatingVerification: Michael McLeroy, 13 Jul 2022

    # Graduated: Verification of requirements
    graduatedVerification: Michael McLeroy, 13 Jul 2022